-- 06_create_gallery.sql
CREATE TABLE IF NOT EXISTS gallery_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id TEXT NOT NULL, 
  image_url TEXT NOT NULL,
  title TEXT,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Note: company_id usually is text (tenantId) in this project structure
