-- Script de Criação das Tabelas no Supabase (PostgreSQL)

-- ── Admin Users ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS admin_users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  email         TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at    TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ── Clients ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS clients (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  phone      TEXT NOT NULL,
  email      TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(email, company_id)
);

-- ── Professionals ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS professionals (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  role        TEXT NOT NULL,
  bio         TEXT,
  photo_url   TEXT,
  specialties JSONB DEFAULT '[]'::jsonb,
  active      BOOLEAN DEFAULT true
);

-- ── Services ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS services (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             TEXT NOT NULL,
  description      TEXT,
  price            NUMERIC(10, 2) NOT NULL,
  duration_minutes INTEGER NOT NULL,
  category         TEXT,
  active           BOOLEAN DEFAULT true
);

-- ── Bookings ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS bookings (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id       BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  professional_id BIGINT REFERENCES professionals(id) ON DELETE SET NULL,
  service_id      BIGINT REFERENCES services(id) ON DELETE SET NULL,
  booking_date    DATE NOT NULL,
  start_time      TIME NOT NULL,
  end_time        TIME NOT NULL,
  status          TEXT DEFAULT 'confirmed',
  notes           TEXT,
  cancel_token    TEXT,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ── Settings ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS settings (
  id            BIGINT PRIMARY KEY DEFAULT 1,
  working_hours JSONB NOT NULL DEFAULT '{"0":null,"1":{"open":"09:00","close":"19:00"},"2":{"open":"09:00","close":"19:00"},"3":{"open":"09:00","close":"19:00"},"4":{"open":"09:00","close":"19:00"},"5":{"open":"09:00","close":"19:00"},"6":{"open":"09:00","close":"17:00"}}'::jsonb,
  slot_interval INTEGER DEFAULT 30,
  salon_data    JSONB
);

-- ── Blocked Dates ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS blocked_dates (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date            DATE NOT NULL,
  reason          TEXT,
  professional_id BIGINT REFERENCES professionals(id) ON DELETE CASCADE
);

-- ── Políticas RLS (Row Level Security) ───────────────────────────────────
-- Estas políticas estão comentadas por padrão. Para usar os recursos do Supabase no Frontend diretamente de forma segura, você precisaria habilitar o RLS e definir as políticas de acesso.
-- Como você tem um backend (servidor Node.js), pode não ser necessário habilitar RLS caso apenas o seu servidor Node acesse o Supabase usando a chave "service_role".
-- 
-- ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE professionals ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE services ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE blocked_dates ENABLE ROW LEVEL SECURITY;
